version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1
      - image: cimg/mariadb:10.6   
    steps:
      - checkout
      - run:
          name: build java application
          command: |
          ./gradlew build
workflows:
  workflow:
    jobs:
    - build
